### PR TITLE
adds a way to go directly to subpages of a repository (Overview, Merge Request,...)

### LINKED ISSUE #11: Add a way to go directly to the categories of the project (Issues, Merge Request,...)
Thanks for the plugin! It's a great time saver, what would also be cool is that if you type `gl yourproject` and then you can select branches, merge-request, issue and it opens the corresponding pages of the project.

### PR DESCRIPTION
**Pull request by tclass**
This fixes [issue 11](https://github.com/lukewaite/alfred-gitlab/issues/11)

### CODE REVIEW

**Comment by lukewaite** [comment]
Thanks - will pull this down today and check it out.

**Comment by lukewaite** [comment]
@tclass are you able to add the updated `info.plist` to the MR? This is what will contain the non-compiled workflow changes.

https://github.com/lukewaite/alfred-gitlab/blob/master/src/info.plist

**Comment by tclass** [comment]
Ahh I already was confused where the non-compiled stuff is :) I added it in the PR

**Comment by lukewaite** [comment]
Cherry-picked the plist change into master. Thanks!

**Comment by lukewaite** [comment]
@tclass Released in [v1.5.0](https://github.com/lukewaite/alfred-gitlab/releases/tag/v1.5.0)

**Comment by Afondevi** [comment]
This send to `blank page` after upgrade Alfred to version 5 :/

**Comment by lukewaite** [comment]
@Afondevi I've just released [v3.0.1](https://github.com/lukewaite/alfred-gitlab/releases/tag/v3.0.1) which seems to fix the issue for me. If that's not the case, can you open a new issue?

**Comment by Afondevi** [comment]
Yes it's perfect !
Thanks @lukewaite !

**Pull request closed without merging**
